/**
 * Full-name queries for the `popular` art pool (`npm run art-pool:build -- --only popular`).
 * Each name is searched against every museum integration in `collect-popular-pool.ts`.
 */
export const POPULAR_ARTIST_NAMES = [
  "Ai Weiwei",
  "Albrecht Dürer",
  "Andy Warhol",
  "Anselm Kiefer",
  "Artemisia Gentileschi",
  "Auguste Rodin",
  "Berthe Morisot",
  "Caravaggio",
  "Claude Monet",
  "Cy Twombly",
  "David Hockney",
  "Diego Rivera",
  "Edgar Degas",
  "Édouard Manet",
  "Edvard Munch",
  "Edward Hopper",
  "Egon Schiele",
  "El Greco",
  "Eugène Delacroix",
  "Francis Bacon",
  "Francisco de Goya",
  "Frida Kahlo",
  "Georges Seurat",
  "Georgia O’Keeffe",
  "Gian Lorenzo Bernini",
  "Gustav Klimt",
  "Gustave Courbet",
  "Henri de Toulouse-Lautrec",
  "Henri Matisse",
  "Hieronymus Bosch",
  "Hilma af Klint",
  "Isamu Noguchi",
  "J. M. W. Turner",
  "Jackson Pollock",
  "Jacques-Louis David",
  "James Turrell",
  "Jan van Eyck",
  "Jasper Johns",
  "Jean-Auguste-Dominique Ingres",
  "Jean-Michel Basquiat",
  "Joan Miró",
  "Joaquín Sorolla",
  "Johannes Vermeer",
  "José Clemente Orozco",
  "Käthe Kollwitz",
  "Katsushika Hokusai",
  "Kazimir Malevich",
  "Keith Haring",
  "Leonardo da Vinci",
  "Louise Bourgeois",
  "Lucian Freud",
  "Marc Chagall",
  "Marcel Duchamp",
  "Mark Rothko",
  "Mary Cassatt",
  "Michelangelo",
  "Odilon Redon",
  "Pablo Picasso",
  "Paul Cézanne",
  "Paul Klee",
  "Pierre-Auguste Renoir",
  "Piet Mondrian",
  "Pieter Bruegel the Elder",
  "Qi Baishi",
  "Raphael",
  "Rembrandt",
  "René Magritte",
  "Robert Rauschenberg",
  "Roy Lichtenstein",
  "Ruth Asawa",
  "Salvador Dalí",
  "Sandro Botticelli",
  "Sonia Delaunay",
  "Takashi Murakami",
  "Titian",
  "Utagawa Hiroshige",
  "Utagawa Yoshifusa",
  "Vincent van Gogh",
  "Wangechi Mutu",
  "Wassily Kandinsky",
  "Willem de Kooning",
  "William Blake",
  "Yayoi Kusama",
] as const;
