/**
 * Shared search seeds for AIC, Cleveland, and Harvard random + pool ingest.
 * Biased toward geography, medium, secular subjects, and global cultures — not
 * European religious painting defaults. Edit here only; all sources stay in sync.
 */
export const SEARCH_TERMS = [
  // Regions & cultures
  "africa",
  "african",
  "alaska",
  "andean",
  "arab",
  "australia",
  "beijing",
  "brazil",
  "cambodia",
  "caribbean",
  "china",
  "cuba",
  "egypt",
  "ethiopia",
  "ghana",
  "guatemala",
  "haiti",
  "hawaii",
  "india",
  "indonesia",
  "inuit",
  "iran",
  "ireland",
  "islamic",
  "istanbul",
  "jamaica",
  "japan",
  "korea",
  "kyoto",
  "london",
  "mexico",
  "mesoamerican",
  "morocco",
  "mumbai",
  "native american",
  "nigeria",
  "oceania",
  "oceanic",
  "osaka",
  "ottoman",
  "peru",
  "persia",
  "philippines",
  "polynesia",
  "scandinavia",
  "seoul",
  "siberia",
  "thailand",
  "tokyo",
  "turkey",
  "ukraine",
  "vietnam",

  // Mediums & object types
  "bronze",
  "ceramic",
  "collage",
  "costume",
  "drawing",
  "engraving",
  "etching",
  "furniture",
  "glass",
  "gouache",
  "ink",
  "jade",
  "jewelry",
  "lacquer",
  "lithograph",
  "manuscript",
  "map",
  "mask",
  "metalwork",
  "miniature",
  "oil",
  "pastel",
  "photograph",
  "porcelain",
  "poster",
  "print",
  "sculpture",
  "tapestry",
  "textile",
  "watercolor",
  "woodcut",

  // Subjects & secular life
  "abstract",
  "american",
  "animal",
  "architecture",
  "beach",
  "bird",
  "bridge",
  "child",
  "city",
  "coast",
  "dance",
  "desert",
  "dog",
  "european",
  "evening",
  "family",
  "fashion",
  "figure",
  "fish",
  "forest",
  "garden",
  "geometric",
  "horse",
  "interior",
  "labor",
  "landscape",
  "man",
  "market",
  "mountain",
  "music",
  "night",
  "ocean",
  "pattern",
  "portrait",
  "river",
  "seascape",
  "ship",
  "sport",
  "still life",
  "storm",
  "street",
  "train",
  "village",
  "winter",
  "woman",

  // Movements & design (sparingly)
  "art deco",
  "art nouveau",
  "baroque",
  "contemporary",
  "cubism",
  "impressionism",
  "modern",
  "renaissance",
  "surrealism",

  // Cities (sample)
  "amsterdam",
  "berlin",
  "cairo",
  "paris",
  "prague",
  "venice",
  "vienna",
] as const;
